### ISSUE TITLE
formatsurations? (In README.md)

### ISSUE THREAD

**Issue by lucaboesch** [gthomas2/moodle-tiny_customstyleformats#1]
What are formatsurations?
🤣

**Comment by gthomas2** [comment]
That's a text copy and replace mistake! Thanks for pointing that out

**Comment by lucaboesch** [comment]
In classes/privacy/provider.php, also the wrong namespace (accessibilitychecker)
is used.
Generally, of course, it would help if this plugin came with CI and Behat tests. You might look at https://github.com/bfh/moodle-tiny_fontcolor to be inspired.

Best,
Luca

**Comment by gthomas2** [comment]
Hi Luca. Thanks for reviewing this for me.
The reason it is so rough is because the timescales were pretty unrealistic for developing the plugin.
Given enough time I would always write PHP unit and behat tests.

**Comment by gthomas2** [comment]
Have fixed privacy provider.php and changed formatsurations in README.md !
